version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"        # Expose frontend on port 3000
    depends_on:
      - backend            # Ensure backend starts before frontend
    networks:
      - app-network        # Shared network

  backend:
    build:
      context: ./backend   # Path to your backend Dockerfile
    ports:
      - "8080:8080"        # Expose backend on port 8080
    networks:
      - app-network        # Shared network

  nginx:
    image: nginx:latest
    user: root    
    ports:
      - "80:80"            # HTTP
      - "443:443"          # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/cudenver-ai.tech/fullchain.pem:/etc/letsencrypt/live/cudenver-ai.tech/fullchain.pem
      - /etc/letsencrypt/live/cudenver-ai.tech/privkey.pem:/etc/letsencrypt/live/cudenver-ai.tech/privkey.pem

    depends_on:
      - backend
      - frontend
    networks:
      - app-network         # Shared network

networks:
  app-network:
    driver: bridge
