version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"        # Map frontend port 3000 to host
    depends_on:
      - backend            # Ensure backend starts before frontend
    networks:
      - app-network        # Shared network

  backend:
    build:
      context: ./backend   # Path to your backend Dockerfile
    ports:
      - "8080:8080"        # Map backend port 8080 to host
    networks:
      - app-network        # Shared network

networks:
  app-network:
    driver: bridge