name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # allow manual runs

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Backend
        id: backend
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" https://your-backend-url.com)
          if [ "$status" -ne 200 ]; then
            echo "Backend is down"
            echo "backend_down=true" >> $GITHUB_OUTPUT
          else
            echo "Backend is up"
            echo "backend_down=false" >> $GITHUB_OUTPUT
          fi

      - name: Check Frontend
        id: frontend
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" https://your-frontend-url.com)
          if [ "$status" -ne 200 ]; then
            echo "Frontend is down"
            echo "frontend_down=true" >> $GITHUB_OUTPUT
          else
            echo "Frontend is up"
            echo "frontend_down=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Discord Alert if Down
        if: steps.backend.outputs.backend_down == 'true' || steps.frontend.outputs.frontend_down == 'true'
        run: |
          content="⚠️ Health Check Alert:\n"
          if [ "${{ steps.backend.outputs.backend_down }}" = "true" ]; then
            content+="❌ Backend is down\n"
          fi
          if [ "${{ steps.frontend.outputs.frontend_down }}" = "true" ]; then
            content+="❌ Frontend is down\n"
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$content\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}